#!/usr/bin/with-contenv bash
set -e
source $BITNAMI_PREFIX/bitnami-utils.sh

if [ ! "$(ls -A $BITNAMI_APP_VOL_PREFIX/conf)" ]; then
  generate_conf_files

  set_manager_password

  print_app_credentials $BITNAMI_APP_NAME manager `print_tomcat_password`
else
  print_container_already_initialized $BITNAMI_APP_NAME
fi

if [ ! -f /app/.initialized ]; then
  initialize_webapps_directory
fi

chown -R $BITNAMI_APP_USER:$BITNAMI_APP_USER $BITNAMI_APP_VOL_PREFIX/conf/ $BITNAMI_APP_VOL_PREFIX/logs/ /app/ || true
