#!/usr/bin/with-contenv bash
set -e
source $BITNAMI_PREFIX/bitnami-utils.sh

rm -rf $BITNAMI_APP_VOL_PREFIX/data/mongod.lock
exec s6-setuidgid $BITNAMI_APP_USER mongod $PROGRAM_OPTIONS ${MONGODB_PASSWORD:+--auth} ${EXTRA_OPTIONS:+"$EXTRA_OPTIONS"}
