FROM docker.io/bitnami/minideb:buster
LABEL maintainer "Bitnami <containers@bitnami.com>"

ENV HOME="/" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-10" \
    OS_NAME="linux"

COPY prebuildfs /
# Install required system packages and dependencies
RUN install_packages acl ca-certificates curl gzip libbz2-1.0 libc6 libffi6 libgcc1 liblzma5 libncursesw6 libreadline7 libsqlite3-0 libssl1.1 libstdc++6 libtinfo6 procps tar zlib1g
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "python" "3.9.11-0" --checksum da372206e2c2635ff79c72cb77e8b2e8ab1cc03066a76f1d1deccd53a332dcbf
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "tensorflow-intel" "2.8.0-1" --checksum 032632f7a59b3d244ee28ee81687507e56b6a6151cb4b1e1e9c993be70bdbc29
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "gosu" "1.14.0-7" --checksum d6280b6f647a62bf6edc74dc8e526bfff63ddd8067dcb8540843f47203d9ccf1
RUN apt-get update && apt-get upgrade -y && \
    rm -r /var/lib/apt/lists /var/cache/apt/archives
RUN chmod g+rwX /opt/bitnami

COPY rootfs /
RUN /opt/bitnami/scripts/tensorflow-intel/postunpack.sh
ENV BITNAMI_APP_NAME="tensorflow-intel" \
    BITNAMI_IMAGE_VERSION="2.8.0-debian-10-r2" \
    PATH="/opt/bitnami/python/bin:/opt/bitnami/common/bin:$PATH"

WORKDIR /app
USER 1001
ENTRYPOINT [ "/opt/bitnami/scripts/tensorflow-intel/entrypoint.sh" ]
CMD [ "python" ]
